---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: share-pv
  namespace: hyperledger
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  nfs:
    path: /nfsserver/share
    server: 161.200.200.231
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: share-pvc
  namespace: hyperledger
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: share-pv