---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    name: share-pv
  name: share-pv
  namespace: hyperledger
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  volumeMode: Filesystem
  nfs:
    path: /nfsserver/share
    server: 161.200.200.231
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: share-pvc
  namespace: hyperledger
spec:
  accessModes:
  - ReadWriteMany
  selector:
    matchLabels:
      name: "share-pv"
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  volumeName: share-pv